#!/bin/bash
# Submit a kfold-final job that skips unsmearing and runs the dual-view classifier set.

SAVE_DIR=${SAVE_DIR:-"checkpoints/unmerge_distr_kfold_unsmear_sweep"}
RUN_NAME=${RUN_NAME:-"kfold_base_det_unsmear"}
K_FOLDS=${K_FOLDS:-5}
KFOLD_ENSEMBLE=${KFOLD_ENSEMBLE:-1}
KFOLD_RANDOM_VALTEST=${KFOLD_RANDOM_VALTEST:-1}
KFOLD_RANDOM_MODE=${KFOLD_RANDOM_MODE:-"jet"}
KFOLD_RANDOM_SEED=${KFOLD_RANDOM_SEED:-42}
N_TRAIN_JETS=${N_TRAIN_JETS:-200000}
MAX_CONSTITS=${MAX_CONSTITS:-80}
MAX_MERGE_COUNT=${MAX_MERGE_COUNT:-10}
TRAIN_PATH=${TRAIN_PATH:-""}
UNMERGE_LOSS=${UNMERGE_LOSS:-"chamfer"}
PHYSICS_WEIGHT=${PHYSICS_WEIGHT:-0.0}
NLL_WEIGHT=${NLL_WEIGHT:-1.0}
NO_DISTRIBUTIONAL=${NO_DISTRIBUTIONAL:-1}
NO_CURRICULUM=${NO_CURRICULUM:-1}
CURR_START=${CURR_START:-2}
CURR_EPOCHS=${CURR_EPOCHS:-20}
USE_TRUE_COUNT=${USE_TRUE_COUNT:-0}
CLASSIFIER_PROFILE=${CLASSIFIER_PROFILE:-"dualview_list"}

export SAVE_DIR RUN_NAME K_FOLDS KFOLD_ENSEMBLE KFOLD_RANDOM_VALTEST KFOLD_RANDOM_MODE KFOLD_RANDOM_SEED \
  N_TRAIN_JETS MAX_CONSTITS MAX_MERGE_COUNT TRAIN_PATH UNMERGE_LOSS PHYSICS_WEIGHT NLL_WEIGHT \
  NO_DISTRIBUTIONAL NO_CURRICULUM CURR_START CURR_EPOCHS USE_TRUE_COUNT CLASSIFIER_PROFILE

sbatch run_unmerge_distr_kfold_final.sh
