#!/bin/bash
set -euo pipefail

# Focused 8-run sweep around the best unsmear regime (v-pred + SNR + cross-attn).

queue() {
  local name="$1"; shift
  local export_list="$1"
  echo "Submitting $name"
  sbatch --export=ALL,${export_list} run_unsmear_single.sh
}

# Base best
queue unsmear_v_base \
  "RUN_NAME=unsmear_v_base,PRED_TYPE=v,SNR_WEIGHT=1,SNR_GAMMA=5.0,SELF_COND_PROB=0.5,COND_DROP_PROB=0.1,JET_LOSS_WEIGHT=0.1,USE_CROSS_ATTN=1,SAMPLING_METHOD=ddim,GUIDANCE_SCALE=1.5,SAMPLE_STEPS=400,N_SAMPLES_EVAL=4"

# Guidance scale variants
queue unsmear_v_g12 \
  "RUN_NAME=unsmear_v_g12,PRED_TYPE=v,SNR_WEIGHT=1,SNR_GAMMA=5.0,SELF_COND_PROB=0.5,COND_DROP_PROB=0.1,JET_LOSS_WEIGHT=0.1,USE_CROSS_ATTN=1,SAMPLING_METHOD=ddim,GUIDANCE_SCALE=1.2,SAMPLE_STEPS=400,N_SAMPLES_EVAL=4"

queue unsmear_v_g20 \
  "RUN_NAME=unsmear_v_g20,PRED_TYPE=v,SNR_WEIGHT=1,SNR_GAMMA=5.0,SELF_COND_PROB=0.5,COND_DROP_PROB=0.1,JET_LOSS_WEIGHT=0.1,USE_CROSS_ATTN=1,SAMPLING_METHOD=ddim,GUIDANCE_SCALE=2.0,SAMPLE_STEPS=400,N_SAMPLES_EVAL=4"

# Self-conditioning variants
queue unsmear_v_sc07 \
  "RUN_NAME=unsmear_v_sc07,PRED_TYPE=v,SNR_WEIGHT=1,SNR_GAMMA=5.0,SELF_COND_PROB=0.7,COND_DROP_PROB=0.1,JET_LOSS_WEIGHT=0.1,USE_CROSS_ATTN=1,SAMPLING_METHOD=ddim,GUIDANCE_SCALE=1.5,SAMPLE_STEPS=400,N_SAMPLES_EVAL=4"

queue unsmear_v_sc03 \
  "RUN_NAME=unsmear_v_sc03,PRED_TYPE=v,SNR_WEIGHT=1,SNR_GAMMA=5.0,SELF_COND_PROB=0.3,COND_DROP_PROB=0.1,JET_LOSS_WEIGHT=0.1,USE_CROSS_ATTN=1,SAMPLING_METHOD=ddim,GUIDANCE_SCALE=1.5,SAMPLE_STEPS=400,N_SAMPLES_EVAL=4"

# Jet loss + SNR gamma tweaks
queue unsmear_v_jet02 \
  "RUN_NAME=unsmear_v_jet02,PRED_TYPE=v,SNR_WEIGHT=1,SNR_GAMMA=5.0,SELF_COND_PROB=0.5,COND_DROP_PROB=0.1,JET_LOSS_WEIGHT=0.2,USE_CROSS_ATTN=1,SAMPLING_METHOD=ddim,GUIDANCE_SCALE=1.5,SAMPLE_STEPS=400,N_SAMPLES_EVAL=4"

queue unsmear_v_snr3 \
  "RUN_NAME=unsmear_v_snr3,PRED_TYPE=v,SNR_WEIGHT=1,SNR_GAMMA=3.0,SELF_COND_PROB=0.5,COND_DROP_PROB=0.1,JET_LOSS_WEIGHT=0.1,USE_CROSS_ATTN=1,SAMPLING_METHOD=ddim,GUIDANCE_SCALE=1.5,SAMPLE_STEPS=400,N_SAMPLES_EVAL=4"

# Heavier inference for final candidate
queue unsmear_v_heavy \
  "RUN_NAME=unsmear_v_heavy,PRED_TYPE=v,SNR_WEIGHT=1,SNR_GAMMA=5.0,SELF_COND_PROB=0.5,COND_DROP_PROB=0.1,JET_LOSS_WEIGHT=0.1,USE_CROSS_ATTN=1,SAMPLING_METHOD=ddim,GUIDANCE_SCALE=1.5,SAMPLE_STEPS=600,N_SAMPLES_EVAL=8"

echo "Queued 8 unsmear runs."
